// <auto-generated />
using System;
using BillsControl.DataAccess.SQLite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BillsControl.DataAccess.SQLite.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250128093130_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("BillsControl.DataAccess.SQLite.Entities.PersonalBillEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BillNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CloseTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OpenTime")
                        .HasColumnType("TEXT");

                    b.Property<float>("PlaceArea")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("PersonalBills");
                });

            modelBuilder.Entity("BillsControl.DataAccess.SQLite.Entities.ResidentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOwner")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PersonalBillId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonalBillId");

                    b.ToTable("Residents");
                });

            modelBuilder.Entity("BillsControl.DataAccess.SQLite.Entities.ResidentEntity", b =>
                {
                    b.HasOne("BillsControl.DataAccess.SQLite.Entities.PersonalBillEntity", "PersonalBill")
                        .WithMany("Residents")
                        .HasForeignKey("PersonalBillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonalBill");
                });

            modelBuilder.Entity("BillsControl.DataAccess.SQLite.Entities.PersonalBillEntity", b =>
                {
                    b.Navigation("Residents");
                });
#pragma warning restore 612, 618
        }
    }
}
