// <auto-generated />
using System;
using BillsControl.DataAccess.SQLite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BillsControl.DataAccess.SQLite.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("BillsControl.Core.Entities.PersonalBillEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BillNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("CloseDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("OpenDate")
                        .HasColumnType("TEXT");

                    b.Property<float>("PlaceArea")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("PersonalBills");
                });

            modelBuilder.Entity("BillsControl.Core.Entities.ResidentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOwner")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PersonalBillId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonalBillNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonalBillId");

                    b.ToTable("Residents");
                });

            modelBuilder.Entity("BillsControl.Core.Entities.ResidentEntity", b =>
                {
                    b.HasOne("BillsControl.Core.Entities.PersonalBillEntity", "PersonalBill")
                        .WithMany("Residents")
                        .HasForeignKey("PersonalBillId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PersonalBill");
                });

            modelBuilder.Entity("BillsControl.Core.Entities.PersonalBillEntity", b =>
                {
                    b.Navigation("Residents");
                });
#pragma warning restore 612, 618
        }
    }
}
